# Generated by Django 5.2.6 on 2025-09-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='cidade',
            new_name='localidade',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='estado',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='rua',
            new_name='uf',
        ),
    ]
